# Generated by Django 3.1.2 on 2020-10-13 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_problem_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='answer',
            field=models.CharField(default='0', max_length=128),
        ),
        migrations.AddField(
            model_name='problem',
            name='symbols',
            field=models.CharField(default='', max_length=128),
        ),
    ]
