# Generated by Django 3.1.2 on 2020-10-13 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_auto_20201013_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='symbols',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
